#! python3  # noqa: E265

"""QDT autocleaner to remove stale resources generated by previous deployments.

Author: Julien Moura (https://github.com/guts)
"""


# #############################################################################
# ########## Libraries #############
# ##################################

# Standard library
import logging
from pathlib import Path
from typing import get_args

# package
from qgis_deployment_toolbelt.constants import (
    DEFAULT_CLEANUP_SCOPES,
    MANAGED_PLUGINS_MANIFEST_FILENAME,
    CleanupScopes,
    DeletionPolicy,
)
from qgis_deployment_toolbelt.jobs.generic_job import GenericJob
from qgis_deployment_toolbelt.plugins.manifest import _read_qdt_managed_plugins_manifest
from qgis_deployment_toolbelt.reports import CleanupReport
from qgis_deployment_toolbelt.utils.trash_or_delete import move_files_to_trash_or_delete


# #############################################################################
# ########## Globals ###############
# ##################################

# logs
logger = logging.getLogger(__name__)


# #############################################################################
# ########## Classes ###############
# ##################################


class JobCleanupManager(GenericJob):
    """Job to remove stale resources left over by previous QDT deployments."""

    ID: str = "cleanup-manager"

    OPTIONS_SCHEMA: dict = {
        "deletion_policy": {
            "type": str,
            "required": False,
            "default": None,
            "possible_values": get_args(DeletionPolicy),
            "condition": "in",
        },
        "dry_run": {
            "type": bool,
            "required": False,
            "default": False,
            "possible_values": None,
            "condition": None,
        },
        "scopes": {
            "type": list,
            "required": False,
            "default": DEFAULT_CLEANUP_SCOPES,
            "possible_values": get_args(CleanupScopes),
            "condition": "all_in",
        },
    }

    def __init__(self, options: dict) -> None:
        """Instantiate the class.

        :param dict options:  job options.
        """
        super().__init__()
        self.options: dict = self.validate_options(options)
        # create report
        self.report = CleanupReport()

    def run(self) -> CleanupReport:
        """Execute job logic.

        Returns:
            CleanupReport: summary of removed/failed resources
        """
        # options
        scopes = self.options.get("scopes", ["plugins_cache"])

        if "plugins_cache" in scopes:
            logger.debug(
                "Cleaning-up outdated plugins archive from local QDT cache folder..."
            )
            self.cleanup_plugins_cache()

        if "plugins_installed" in scopes:
            logger.debug("Cleaning-up outdated plugins from installed QGIS profiles...")
            self.cleanup_plugins_installed()

        if "profiles_deprecated" in scopes:
            logger.debug("Cleaning-up installed QGIS profiles flagged as deprecated...")
            self.cleanup_profiles_deprecated()

        # remove files/folders
        self._remove_paths()

        logger.info(
            f"Job {self.ID} ran successfully. "
            f"{len(self.report.removed)} resource(s) removed"
            f"{' (dry-run, nothing actually deleted)' if self.options.get('dry_run', False) else ''}, "
            f"{len(self.report.failed)} failure(s)."
        )
        return self.report

    # -- INTERNAL LOGIC ------------------------------------------------------
    def _referenced_plugin_ids(self) -> set[str]:
        """Union of plugin identifiers (id_with_version) referenced by every
        installed and downloaded profile currently known to QDT.

        Returns:
            set[str]: set of plugin identifiers (as used in archive filenames and
                installation folder names)
        """
        referenced: set[str] = set()
        for lister in (self.list_installed_profiles, self.list_downloaded_profiles):
            profiles = lister(quiet=True)
            if not profiles:
                continue
            for profile in profiles:
                referenced.update(p.id_with_version for p in profile.plugins)
        return referenced

    def _referenced_plugin_installation_folders(self) -> set[Path]:
        """Union of plugin installation path referenced by every installed
        and downloaded profile currently known to QDT.

        Returns:
            set[Path]: plugin folder paths
        """
        referenced: set[Path] = set()
        for lister in (self.list_installed_profiles, self.list_downloaded_profiles):
            profiles = lister(quiet=True)
            if not profiles:
                continue
            for profile in profiles:
                referenced.update(
                    profile.path_in_qgis.joinpath(
                        "python/plugins", p.installation_folder_name
                    )
                    for p in profile.plugins
                )
        return referenced

    def cleanup_plugins_cache(self) -> None:
        """Remove plugin archives from the QDT plugins cache folder which are not
        referenced by any installed or downloaded profile anymore.
        """
        if not self.qdt_plugins_folder.is_dir():
            logger.debug(
                f"QDT plugins cache folder does not exist: {self.qdt_plugins_folder}"
            )
            return

        referenced_ids = self._referenced_plugin_ids()

        logger.debug(
            f"{len(referenced_ids)} plugin(s) currently referenced by installed "
            "or downloaded profiles."
        )
        for archive in sorted(self.qdt_plugins_folder.glob("*.zip")):
            if archive.stem in referenced_ids:
                continue
            self.report.removed.append(archive)

    def cleanup_plugins_installed(self) -> None:
        """Remove stale plugin folders from installed QGIS profiles.

        Only plugins listed in QDT managed plugins manifests are considered for
        cleanup. Third-party plugins manually installed by users are ignored.
        """
        installed_profiles = self.list_installed_profiles(quiet=True)
        if not installed_profiles:
            logger.debug("No installed profile found for plugins cleanup.")
            return

        referenced_folders = self._referenced_plugin_installation_folders()
        logger.debug(
            f"{len(referenced_folders)} installed plugin folder name(s) currently "
            "referenced by installed or downloaded profiles."
        )

        for profile in installed_profiles:
            profile_plugins_folder = profile.path_in_qgis.joinpath("python/plugins")
            if not profile_plugins_folder.is_dir():
                logger.debug(
                    f"No plugins folder found under profile '{profile.name}': {profile_plugins_folder}"
                )
                continue

            manifest_path = profile_plugins_folder.joinpath(
                MANAGED_PLUGINS_MANIFEST_FILENAME
            )
            managed_plugins = _read_qdt_managed_plugins_manifest(manifest_path)
            if not managed_plugins:
                logger.debug(
                    f"No plugins managed by QDT in profile '{profile.name}' "
                    f"('{profile.path_in_qgis}'). Skipping cleanup of this profile."
                )
                continue

            for plugin_folder_name in sorted(managed_plugins):
                plugin_path = profile_plugins_folder / plugin_folder_name
                if not plugin_path.exists() or plugin_path in referenced_folders:
                    continue

                self.report.removed.append(plugin_path)

    def cleanup_profiles_deprecated(self) -> None:
        """Remove installed QGIS profiles which are flagged as deprecated."""
        qgis_profiles_path = self.qgis_profiles_path.resolve()
        if not qgis_profiles_path.is_dir():
            logger.debug(f"QGIS profiles folder does not exist: {qgis_profiles_path}")
            return

        already_listed: set[Path] = set()

        for profile in (
            *self.scan_profiles_folder(start_parent_folder=qgis_profiles_path),
            *self.scan_profiles_folder(
                start_parent_folder=self.qdt_downloaded_repositories
            ),
        ):
            if not profile.is_deprecated:
                continue

            installed_profile_folder = self._get_installed_profile_folder(
                profile=profile
            )
            if (
                installed_profile_folder is None
                or installed_profile_folder in already_listed
            ):
                continue

            logger.info(
                f"Profile '{profile.name}' is flagged as deprecated: its installed "
                f"folder is going to be removed: {installed_profile_folder}"
            )
            already_listed.add(installed_profile_folder)
            self.report.removed.append(installed_profile_folder)

    def _get_installed_profile_folder(self, profile: QdtProfile) -> Path | None:
        """Determine the installed folder of a profile, whether it has been loaded
            from the QGIS profiles folder or from the QDT downloaded repositories,
            making sure it's safe to remove it.

        Args:
            profile (QdtProfile): profile to get the installed folder for

        Returns:
            Path | None: path to the profile folder within the QGIS profiles
                folder. None if it can't be determined, if it's located out of the
                QGIS profiles folder or if the profile is not installed.
        """
        qgis_profiles_path = self.qgis_profiles_path.resolve()

        if isinstance(profile.folder, Path) and profile.folder.is_relative_to(
            qgis_profiles_path
        ):
            installed_profile_folder = profile.folder
        elif isinstance(profile.name, str) and len(profile.name):
            # resolved to neutralize a name which would escape the profiles folder
            installed_profile_folder = qgis_profiles_path.joinpath(
                profile.name
            ).resolve()
        else:
            logger.error(
                "Unable to determine the installed folder of the profile stored "
                f"in {profile.folder}: it has no usable name."
            )
            return None

        # safety net: never remove anything out of the QGIS profiles folder, nor
        # the QGIS profiles folder itself
        if installed_profile_folder == qgis_profiles_path or not (
            installed_profile_folder.is_relative_to(qgis_profiles_path)
        ):
            logger.error(
                f"Folder of the profile '{profile.name}' is not located within the "
                f"QGIS profiles folder ({qgis_profiles_path}), so it's ignored: "
                f"{installed_profile_folder}"
            )
            return None

        if not installed_profile_folder.is_dir():
            logger.debug(
                f"Profile '{profile.name}' is flagged as deprecated but it's not "
                f"installed: {installed_profile_folder}"
            )
            return None

        return installed_profile_folder

    def _remove_paths(self) -> None:
        """Remove files and folders listed in the ``self.report.removed``."""

        # in dry mode, just log what would be removed, without actually removing anything
        if self.options.get("dry_run", False):
            for path_to_be_removed in self.report.removed:
                logger.info(f"[dry-run] Would remove: {path_to_be_removed}")
            return

        # remove files/folders
        logger.debug(f"Removing {len(self.report.removed)} path(s)")
        self.report.failed = move_files_to_trash_or_delete(
            files_to_trash=self.report.removed,
            policy=self.options.get("deletion_policy"),
        )
