#! python3  # noqa: E265

"""QDT autocleaner to remove stale resources generated by previous deployments.

Author: Julien Moura (https://github.com/guts)
"""


# #############################################################################
# ########## Libraries #############
# ##################################

# Standard library
import logging
from dataclasses import dataclass, field
from pathlib import Path

# package
from qgis_deployment_toolbelt.jobs.generic_job import GenericJob
from qgis_deployment_toolbelt.utils.file_stats import is_file_older_than
from qgis_deployment_toolbelt.utils.trash_or_delete import move_files_to_trash_or_delete


# #############################################################################
# ########## Globals ###############
# ##################################

# logs
logger = logging.getLogger(__name__)


# #############################################################################
# ########## Classes ###############
# ##################################


@dataclass
class CleanupReport:
    """Structure to summarize a cleanup."""

    removed: list[Path] = field(default_factory=list)
    failed: list[tuple[Path, str]] = field(default_factory=list)
    skipped: list[Path] = field(default_factory=list)

    def __len__(self) -> int:
        """Number of resources actually removed (or that would be, in dry-run mode).

        Returns:
            int: count of removed resources
        """
        return len(self.removed)


class JobCleanupManager(GenericJob):
    """Job to remove stale resources left over by previous QDT deployments."""

    ID: str = "qdt-autoclean"
    OPTIONS_SCHEMA: dict = {
        "targets": {
            "type": (list, str),
            "required": False,
            "default": ["qdt_logs", "plugins_cache", "plugins_installed"],
            "possible_values": (
                "qdt_logs",
                "plugins_cache",
                "plugins_installed",
                "repositories",
            ),
            "condition": None,
        },
        "dry_run": {
            "type": bool,
            "required": False,
            "default": False,
            "possible_values": None,
            "condition": None,
        },
        "report": {
            "type": bool,
            "required": False,
            "default": True,
            "possible_values": None,
            "condition": None,
        },
        "repositories_retention_days": {
            "type": int,
            "required": False,
            "default": 30,
            "possible_values": None,
            "condition": None,
        },
    }

    def __init__(self, options: dict) -> None:
        """Instantiate the class.

        :param dict options:  job options.
        """
        super().__init__()
        self.options: dict = self.validate_options(options)

    def run(self) -> CleanupReport:
        """Execute job logic.

        Returns:
            CleanupReport: summary of removed/failed/skipped resources
        """
        targets = self.options.get("targets") or [
            "plugins_cache",
            "plugins_installed",
        ]
        if isinstance(targets, str):
            targets = [targets]
        dry_run: bool = self.options.get("dry_run", False)

        report = CleanupReport()

        if "plugins_cache" in targets:
            self.cleanup_plugins_cache(dry_run=dry_run, report=report)

        if "plugins_installed" in targets:
            self.cleanup_installed_plugins(dry_run=dry_run, report=report)

        if "repositories" in targets:
            self.cleanup_repositories(
                dry_run=dry_run,
                retention_days=self.options.get("repositories_retention_days", 30),
                report=report,
            )

        logger.info(
            f"Job {self.ID} ran successfully. "
            f"{len(report.removed)} resource(s) removed"
            f"{' (dry-run, nothing actually deleted)' if dry_run else ''}, "
            f"{len(report.failed)} failure(s)."
        )
        return report

    # -- INTERNAL LOGIC ------------------------------------------------------
    def _referenced_plugin_ids(self) -> set[str]:
        """Union of plugin identifiers (id_with_version) referenced by every
        installed and downloaded profile currently known to QDT.

        Returns:
            set[str]: set of plugin identifiers (as used in archive filenames and
                installation folder names)
        """
        referenced: set[str] = set()
        for lister in (self.list_installed_profiles, self.list_downloaded_profiles):
            profiles = lister()
            if not profiles:
                continue
            for profile in profiles:
                referenced.update(p.id_with_version for p in profile.plugins)
        return referenced

    def cleanup_plugins_cache(self, dry_run: bool, report: CleanupReport) -> None:
        """Remove plugin archives from the QDT plugins cache folder which are not
        referenced by any installed or downloaded profile anymore.

        Args:
            dry_run (bool): if True, only report what would be removed
            report (CleanupReport): report to update in place
        """
        if not self.qdt_plugins_folder.is_dir():
            logger.debug(
                f"QDT plugins cache folder does not exist: {self.qdt_plugins_folder}"
            )
            return

        referenced_ids = self._referenced_plugin_ids()
        logger.debug(
            f"{len(referenced_ids)} plugin(s) currently referenced by installed "
            "or downloaded profiles."
        )

        for archive in sorted(self.qdt_plugins_folder.glob("*.zip")):
            if archive.stem in referenced_ids:
                continue
            self._remove_path(archive, dry_run=dry_run, report=report)

    def cleanup_installed_plugins(self, dry_run: bool, report: CleanupReport) -> None:
        """Remove plugin folders installed within QGIS profiles which are no longer
        referenced by the corresponding profile.json.

        Args:
            dry_run (bool): if True, only report what would be removed
            report (CleanupReport): report to update in place
        """
        installed_profiles = self.list_installed_profiles()
        if not installed_profiles:
            logger.debug("No installed profile found. Nothing to clean up.")
            return

        for profile in installed_profiles:
            plugins_folder = profile.folder / "python/plugins"
            if not plugins_folder.is_dir():
                continue

            expected_folders = {p.installation_folder_name for p in profile.plugins}

            for plugin_folder in sorted(plugins_folder.iterdir()):
                if not plugin_folder.is_dir():
                    continue
                # never touch dunder/hidden folders (__pycache__, .cache, etc.)
                if plugin_folder.name.startswith(("__", ".")):
                    continue
                if plugin_folder.name in expected_folders:
                    continue
                logger.debug(
                    f"Profile {profile.name} - plugin folder '{plugin_folder.name}' "
                    "is not referenced in profile.json anymore."
                )
                self._remove_path(plugin_folder, dry_run=dry_run, report=report)

    def cleanup_repositories(
        self, dry_run: bool, retention_days: int, report: CleanupReport
    ) -> None:
        """Remove downloaded repositories (scenario cache under the QDT working
        folder) that have not been modified within the retention period.

        Args:
            dry_run (bool): if True, only report what would be removed
            retention_days (int): minimum age (in days) before a repository folder
                is considered stale
            report (CleanupReport): report to update in place
        """
        repositories_parent = self.qdt_working_folder / "repositories"
        if not repositories_parent.is_dir():
            logger.debug(f"No repositories cache folder found: {repositories_parent}")
            return

        retention_seconds = max(retention_days, 0) * 86400
        now = time()

        for repo_folder in sorted(repositories_parent.iterdir()):
            if not repo_folder.is_dir():
                continue
            try:
                last_modified = repo_folder.stat().st_mtime
            except OSError as err:
                logger.warning(f"Unable to stat {repo_folder}. Trace: {err}")
                continue

            if (now - last_modified) < retention_seconds:
                logger.debug(
                    f"{repo_folder} is younger than the retention period "
                    f"({retention_days} day(s)). Keeping it."
                )
                report.skipped.append(repo_folder)
                continue

            self._remove_path(repo_folder, dry_run=dry_run, report=report)

    @staticmethod
    def _remove_path(path: Path, dry_run: bool, report: CleanupReport) -> None:
        """Remove a file or folder, updating the report accordingly.

        Args:
            path (Path): path to remove
            dry_run (bool): if True, don't actually remove anything
            report (CleanupReport): report to update in place
        """
        if dry_run:
            logger.info(f"[dry-run] Would remove: {path}")
            report.removed.append(path)
            return

        move_files_to_trash_or_delete([path])

    def cleanup_logs(self, dry_run: bool, report: CleanupReport) -> None:
        """Remove plugin folders installed within QGIS profiles which are no longer
        referenced by the corresponding profile.json.

        Args:
            dry_run (bool): if True, only report what would be removed
            report (CleanupReport): report to update in place
        """
        for log_file in self.qdt_logs_folder.glob("*.log"):
            if is_file_older_than(
                local_file_path=log_file,
                expiration_rotating_hours=self.options.get("delay", 730),
            ):
                logger.debug(f"Autoclean - LOGS - Outdated file: {log_file}")
                li_files_to_be_deleted.append(log_file)

        # clean plugins archives
        for plugin_archive in self.qdt_plugins_folder.glob("*.zip"):
            if is_file_older_than(
                local_file_path=plugin_archive,
                expiration_rotating_hours=self.options.get("delay", 730),
            ):
                logger.debug(
                    f"Autoclean - PLUGIN ARCHIVE - Outdated file: {plugin_archive}"
                )
                li_files_to_be_deleted.append(plugin_archive)

        move_files_to_trash_or_delete(files_to_trash=li_files_to_be_deleted)
