#! python3  # noqa: E265

"""
Sub-command to clean up outdated resources generated by previous deployments.

Author: Julien Moura (https://github.com/guts)
"""


# ############################################################################
# ########## IMPORTS #############
# ################################

# standard library
import argparse
import logging
from os import getenv
from typing import TYPE_CHECKING, get_args

# package
from qgis_deployment_toolbelt.constants import (
    DEFAULT_CLEANUP_SCOPES,
    DEFAULT_DELETION_POLICY,
    CleanupScopes,
    DeletionPolicy,
)
from qgis_deployment_toolbelt.jobs.job_cleanup_manager import JobCleanupManager
from qgis_deployment_toolbelt.utils.bouncer import exit_cli_error, exit_cli_success


if TYPE_CHECKING:
    from qgis_deployment_toolbelt.jobs.job_cleanup_manager import CleanupReport

# ############################################################################
# ########## GLOBALS #############
# ################################

logger = logging.getLogger(__name__)


# ############################################################################
# ########## CLI #################
# ################################


def parser_cleanup(
    subparser: argparse.ArgumentParser,
) -> argparse.ArgumentParser:
    """Set the argument parser for subcommand.

    Args:
        subparser (argparse.ArgumentParser): parser to set up

    Returns:
        argparse.ArgumentParser: parser ready to use
    """
    subparser.add_argument(
        "--deletion-policy",
        help="Deletion policy applied to resources actually removed by this cleanup. "
        "Can also be set with the 'QDT_DELETION_POLICY' environment variable. "
        f"Defaults to '{DEFAULT_DELETION_POLICY}'.",
        choices=get_args(DeletionPolicy),
        dest="cleanup_deletion_policy",
        default=getenv("QDT_DELETION_POLICY", DEFAULT_DELETION_POLICY),
    )

    subparser.add_argument(
        "--dry-run",
        help="Only display what would be removed, without deleting anything. "
        "Defaults to False.",
        action="store_true",
        dest="cleanup_dry_run",
        default=False,
    )

    subparser.add_argument(
        "--scope",
        help="Scope of the cleanup. Repeat the option to combine several scopes. "
        f"Defaults to '{DEFAULT_CLEANUP_SCOPES}'.",
        choices=get_args(CleanupScopes),
        action="append",
        dest="cleanup_scope",
        default=DEFAULT_CLEANUP_SCOPES,
    )

    subparser.set_defaults(func=run)

    return subparser


# ############################################################################
# ########## MAIN ################
# ################################


def run(args: argparse.Namespace) -> None:
    """Run the sub command logic.

    Args:
        args (argparse.Namespace): arguments passed to the subcommand
    """
    logger.debug(f"Running {args.command} with {args}")

    # map job optins from CLI args
    options: dict = {
        "deletion_mode": args.cleanup_deletion_policy,
        "dry_run": args.cleanup_dry_run,
        "scopes": args.cleanup_scope,
    }

    # run
    try:
        job = JobCleanupManager(options=options)
        cleanup_report: CleanupReport = job.run()
    except Exception as err:
        exit_cli_error(err)

    # report
    if cleanup_report.removed or cleanup_report.failed:
        print(cleanup_report)  # noqa: T201
    else:
        print("Nothing to clean up.")  # noqa: T201

    exit_cli_success("Cleanup achieved!")
