#! python3  # noqa: E265

"""
Sub-command to clean up outdated resources generated by previous deployments.

Author: Julien Moura (https://github.com/guts)
"""


# ############################################################################
# ########## IMPORTS #############
# ################################

# standard library
import argparse
import logging

# package
from qgis_deployment_toolbelt.jobs.job_autoclean import JobCleanupManager
from qgis_deployment_toolbelt.utils.bouncer import exit_cli_error, exit_cli_success


# ############################################################################
# ########## GLOBALS #############
# ################################

logger = logging.getLogger(__name__)


# ############################################################################
# ########## CLI #################
# ################################


def parser_cleanup(
    subparser: argparse.ArgumentParser,
) -> argparse.ArgumentParser:
    """Set the argument parser for subcommand.

    Args:
        subparser (argparse.ArgumentParser): parser to set up

    Returns:
        argparse.ArgumentParser: parser ready to use
    """
    subparser.add_argument(
        "--scope",
        help="Scope of the cleanup. Repeat the option to combine several scopes. "
        "Defaults to 'orphaned_plugins' and 'plugins_cache'.",
        choices=("orphaned_plugins", "plugins_cache", "repositories_cache"),
        action="append",
        dest="cleanup_scope",
        default=None,
    )
    subparser.add_argument(
        "--dry-run",
        help="Only display what would be removed, without deleting anything.",
        action="store_true",
        dest="cleanup_dry_run",
    )

    subparser.set_defaults(func=run)

    return subparser


# ############################################################################
# ########## MAIN ################
# ################################


def run(args: argparse.Namespace) -> None:
    """Run the sub command logic.

    Args:
        args (argparse.Namespace): arguments passed to the subcommand
    """
    logger.debug(f"Running {args.command} with {args}")

    options: dict = {"dry_run": args.cleanup_dry_run}
    if args.cleanup_scope:
        options["scope"] = args.cleanup_scope

    try:
        job = JobCleanupManager(options=options)
        job.run()
        exit_cli_success("Cleanup achieved!")
    except Exception as err:
        exit_cli_error(err)
